name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: jiwooproity/engineer-porfolio-3d
          stage: main
          yaml: |
            name: notion-client-proxy
            app: node@16
            options:
              env:
                - name: NODE_ENV
                  value: production
                - name: NOTION_TOKEN
                  value: secret_dFQXuHrWwxLNdD6hzdNPhJm3syysmqoDH53aBZEc7Yb
                - name: NOTION_DATABASE_ID
                  value: 286a6f67dcbb48c79d5a02b6b812da4a
              ports: "8080"
              install: npm install
              build: npm run build
              start: npm run start
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: node
