name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install yarn package manager
        run: npm i -g yarn
      - name: Install package.json dependencies
        run: yarn install
      - name: Run to vitest testing
        run: yarn run test
        env:
          AUDIO_BASE_PATH: ${{ secrets.AUDIO_BASE_PATH }}
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: jiwooproity/engineer-portfolio
          stage: main
          yaml: |
            name: notion-client-proxy
            app: node@16
            options:
              env:
                - name: NODE_ENV
                  value: production
                - name: AUDIO_BASE_PATH
                  value: ${{ secrets.AUDIO_BASE_PATH }}
                - name: NOTION_TOKEN
                  value: ${{ secrets.NOTION_TOKEN }}
                - name: NOTION_DATABASE_ID
                  value: ${{ secrets.NOTION_DATABASE_ID }}
              ports: "8080"
              install: npm install
              build: npm run build
              start: npm run start
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: node
